In [1]:
import numpy as np

In [6]:
#printing array with all ones in a general way
mx_1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
#printing array 
mx_1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
#printing ones matrix using column (bydefault float)
mx_1=np.ones(5)
print(mx_1)

[1. 1. 1. 1. 1.]


In [10]:
mx_1.dtype

dtype('float64')

In [17]:
#printing one's matrix using column and row number
mx_1=np.ones((5,5))
print(mx_1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#converting data type to int
mx_1=np.ones((3,4),dtype=int)
print(mx_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
#converting data type to float
mx_1=np.ones((3,4),dtype=float)
print(mx_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
#converting data type to string
mx_1=np.ones((3,4),dtype=str)
print(mx_1)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [27]:
#printing matrix with all zero
mx_0=np.zeros(5)
print(mx_0)

[0. 0. 0. 0. 0.]


In [29]:
#printing matrix with all zero
mx_0=np.zeros((5,9))
print(mx_0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
#converting data type to int
mx_1=np.zeros((3,4),dtype=int)
print(mx_1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
#converting data type to boolean
mx_1=np.zeros((3,4),dtype=bool)
print(mx_1)

[[False False False False]
 [False False False False]
 [False False False False]]


In [32]:
#converting data type to string
mx_1=np.zeros((3,4),dtype=str)
print(mx_1)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [40]:
#creating an empty matrix
mx_empty=np.empty((5))
print(mx_empty)

[2.07507571e-322 3.97228779e-321 4.45047026e-308 4.81693045e-312
 9.45734481e-308]


In [41]:
#creating an empty matrix
mx_empty=np.empty((5,4))
print(mx_empty)

[[3.84988051e-316 6.27463370e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.30276956e+180 1.57076922e-076 4.57487963e-071]
 [4.26362806e-086 3.35558548e-143 6.01433264e+175 6.93885958e+218]
 [5.56218858e+180 3.94356143e+180 2.00264363e-076 4.32103292e-037]
 [6.16180616e-042 9.20819071e+169 7.43571620e-144 1.50008929e+248]]
