# Functions:-

In [1]:
import numpy as np

# arange(start,end,step)

In [6]:
#arranging array from 1 to 13
arr1=np.arange(1,13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
#printing odd array
odd=np.arange(1,13,2)
print(odd)

[ 1  3  5  7  9 11]


In [11]:
#printing even array
even=np.arange(2,13,2)
print(even)

[ 2  4  6  8 10 12]


# linspace(start,end,space)

In [17]:
#Equal spacing between 1 and 10 of 4
space=np.linspace(1,10,4)
print(space)

[ 1.  4.  7. 10.]


In [18]:
#Equal spacing between 1 and 5 of 4
space=np.linspace(1,5,4)
print(space)

[1.         2.33333333 3.66666667 5.        ]


# reshape()

In [22]:
#1 d array
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
#coverting 1 d array to 2 d
arr_2d=arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
#coverting 1 d array to 2 d
arr_2d=arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#coverting 1 d array to 3 d
arr_3d=arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
#coverting 1 d array to 3 d
arr_3d=arr_1d.reshape(1,6,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [41]:
#coverting 1 d array to 2 d
ar1=np.arange(1,13).reshape(3,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#coverting 1 d array to 3 d
ar=np.arange(1,13).reshape(3,4).reshape(1,6,2)
print(ar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


# flatten()

In [35]:
#convert the array to 1 d
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
#convert the array to 1 d in same order
ar.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
#convert the array to 1 d using column order
ar.flatten(order='F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [44]:
#convert the array to 1 d using column order
ar1.flatten(order='F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

# ravel()

In [45]:
#convert the array to 1d
#faster then flatten()
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [53]:
arr_2d=arr_1d.reshape(2,6)
print(arr_2d)
arr_2d.transpose()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [54]:
arr_3d=arr_1d.reshape(2,3,2)
print(arr_3d)
arr_3d.transpose()

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])