# Mathematical Functions:

In [1]:
import numpy as np

In [5]:
#creating 2 d array
arr1=np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
#creating 2 d array
arr2=np.arange(13,25).reshape(3,4)
arr2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [25]:
#adding two matrix
arr1+arr2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [14]:
#adding two matrix
np.add(arr1,arr2)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [15]:
#subtracting two matrix
arr1-arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [16]:
#subtracting two matrix
np.subtract(arr2,arr1)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [17]:
#dividing two matrix
arr1/arr2

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

In [18]:
#dividing two matrix
np.divide(arr2,arr1)

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

In [19]:
#multiplying two matrix
arr1*arr2

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [20]:
#multiplying two matrix
np.multiply(arr1,arr2)

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [32]:
#finding maximum value of the matrix
arr1.max()

12

In [33]:
#finding maximum value of the matrix
arr2.max()

24

In [34]:
#finding the index value of the maximum value of the matrix
arr1.argmax()

11

In [45]:
#printing maximum values column wise
print(arr1)
arr1.max(axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 9, 10, 11, 12])

In [46]:
#printing maximum values column wise
arr3=np.array([[1,56,2,4,56,23],[23,78,23,56,2,3]])
print(arr3)
arr3.max(axis=0)

[[ 1 56  2  4 56 23]
 [23 78 23 56  2  3]]


array([23, 78, 23, 56, 56, 23])

In [50]:
#printing maximum values row wise
arr1.max(axis=1)

array([ 4,  8, 12])

In [52]:
#finding minimum value of the matrix
arr1.min()

1

In [54]:
#finding the index value of the minimum value of the matrix
arr1.argmin()

0

In [57]:
#printing minimum values column wise
print(arr1)
arr1.min(axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([1, 2, 3, 4])

In [58]:
#printing minimum values row wise
print(arr1)
arr1.min(axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([1, 5, 9])

In [59]:
#add all the elements of the array
arr1.sum()

78

In [62]:
#add all the elements in  column
print(arr1)
np.sum(arr1,axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([15, 18, 21, 24])

In [63]:
#add all the elements in row
print(arr1)
np.sum(arr1,axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([10, 26, 42])

In [64]:
#find the mean of an array
#mean=(sum of all the elements)/total number of elements
arr1.mean()

6.5

In [66]:
#square root of all the elements
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [71]:
#find standard deviation
#it will help us to know the variation between the mean value and the deviation of every other value to it
print(arr1)
np.std(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3.452052529534663

In [72]:
#exponent of each element 
#to shorten the repeated the multiplication
print(arr1)
np.exp(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [78]:
#inverse of the exponent
#used to know the variations of values by plotting graphs
print(arr1)
np.log(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [79]:
#log base 10 of each element 
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])