# Slicing Function()

In [3]:
import numpy as np

In [6]:
#printing 10 x 10 matrix
mx=np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [7]:
#printing 0th row , 0th column value
mx[0,0]

1

In [8]:
#scalar value
mx[0,0].ndim

0

In [11]:
#getting single row
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#check dimension of the matrix
mx[0].ndim

1

In [14]:
#all rows but Oth column
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
#slicing to get 2d array
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [21]:
#slicing to get 2d array
mx[7:,0:8]

array([[71, 72, 73, 74, 75, 76, 77, 78],
       [81, 82, 83, 84, 85, 86, 87, 88],
       [91, 92, 93, 94, 95, 96, 97, 98]])

In [22]:
#check dimension of the matrix
mx[:,0:1].ndim

2

In [23]:
#check dimension of the matrix
mx[7:,0:8].ndim

2

In [24]:
#slicing to get 2d array
mx[0:4,0:4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [25]:
#slicing to get 2d array
mx[:,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [31]:
#to access the whole matrix
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
#to access the whole matrix 
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
#to access the whole matrix
mx[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [34]:
#how much size does each element occupies in system
mx.itemsize

4

In [35]:
#to know the data type of matrix 
mx.dtype

dtype('int32')

# Concatenation and split Function()

In [36]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [38]:
arr2=np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [44]:
#concatenation of list
list=[1,2,3,4]
list1=[5,6,7,8]
list+list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [41]:
#+ will add all the elements values accordingly
print(arr1+arr2)

[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [45]:
#to concatenate two array
print(np.concatenate((arr1,arr2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [49]:
#concatenate column wise
print(np.concatenate((arr1,arr2,arr1),axis=1))

[[ 1  2  3  4 17 18 19 20  1  2  3  4]
 [ 5  6  7  8 21 22 23 24  5  6  7  8]
 [ 9 10 11 12 25 26 27 28  9 10 11 12]
 [13 14 15 16 29 30 31 32 13 14 15 16]]


In [47]:
#vertical
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [51]:
#horizontal
np.hstack((arr1,arr2,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 29, 30, 31, 32]])

In [59]:
#spliting array
print(np.split(arr1,4))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


In [62]:
#type of the splitted array
ax=np.split(arr1,4)
type(ax)

list

In [63]:
#printing the list
ax[0]

array([[1, 2, 3, 4]])

In [64]:
#printing the list
ax[1]

array([[5, 6, 7, 8]])

In [65]:
#printing the list
ax[2]

array([[ 9, 10, 11, 12]])

In [66]:
#printing the list
ax[3]

array([[13, 14, 15, 16]])

In [67]:
#type of list
type(ax[0])

numpy.ndarray

In [68]:
#spltiitng row wise
print(np.split(arr1,2,axis=0))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [69]:
#spltiitng column wise
print(np.split(arr1,2,axis=1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [70]:
#creating 1 d array
d1=np.array([1,2,3,4,5,6,7,8])
print(d1)

[1 2 3 4 5 6 7 8]


In [73]:
#splitting 1 d array in many arrays
print(np.split(d1,[1,4]))

[array([1]), array([2, 3, 4]), array([5, 6, 7, 8])]
