In [1]:
import numpy as np
#uses to generate otp
import random 

In [12]:
#to generate random number
np.random.random(1)

array([0.79209116])

In [13]:
#for 2 d array
np.random.random((3,3))

array([[0.93309552, 0.54384018, 0.46844781],
       [0.21723371, 0.87396721, 0.33569676],
       [0.84266702, 0.81899779, 0.71434109]])

In [28]:
#integer values between 1 and 4
np.random.randint(1,4)

3

In [33]:
#2 d array 
np.random.randint(1,4,(4,4))

array([[3, 1, 2, 3],
       [1, 2, 2, 1],
       [3, 2, 1, 3],
       [2, 2, 2, 2]])

In [41]:
#3 d array
np.random.randint(1,4,(1,4,4))

array([[[2, 3, 2, 3],
        [2, 3, 1, 2],
        [1, 2, 1, 3],
        [3, 1, 1, 3]]])

In [42]:
#to generate the same random pattern again maximum 2^32-1 pattern
np.random.seed(6)
np.random.randint(1,4,(1,4,4))

array([[[3, 2, 1, 3],
        [2, 3, 1, 3],
        [2, 2, 2, 2],
        [3, 2, 1, 3]]])

In [43]:
#to generate the same random pattern again
np.random.seed(6)
np.random.randint(1,4,(1,4,4))

array([[[3, 2, 1, 3],
        [2, 3, 1, 3],
        [2, 2, 2, 2],
        [3, 2, 1, 3]]])

In [44]:
np.random.seed(9)
np.random.randint(1,4,(1,4,4))

array([[[3, 1, 3, 2],
        [3, 1, 3, 2],
        [2, 3, 1, 1],
        [3, 2, 1, 2]]])

In [50]:
np.random.seed(6)
np.random.randint(1,4,(1,4,4))

array([[[3, 2, 1, 3],
        [2, 3, 1, 3],
        [2, 2, 2, 2],
        [3, 2, 1, 3]]])

In [52]:
np.random.rand(1)

array([0.43814143])

In [54]:
#values ranging between 0 and 1
np.random.rand(2,5)

array([[0.73588211, 0.51803641, 0.5788586 , 0.6453551 , 0.99022427],
       [0.8198582 , 0.41320093, 0.87626766, 0.82375943, 0.05447451]])

In [55]:
#values ranging between -1 and 1
np.random.randn(2,5)

array([[ 0.87722778,  0.63472317,  0.89879299,  1.01601327, -1.05448739],
       [ 0.11505911, -0.10678997,  0.50517128,  0.70734113, -0.92146499]])

In [58]:
#choices between the given ranges only
x=[1,2,3,4,5]
for i in range(20):
    print(np.random.choice(x))

2
1
1
3
4
5
4
1
2
5
3
5
2
4
2
2
5
1
3
1


In [59]:
#permutation - arranging in some sequence
for i in range(20):
    print(np.random.permutation(x))

[4 1 3 5 2]
[4 3 1 5 2]
[3 1 4 2 5]
[5 1 2 3 4]
[5 3 4 1 2]
[2 1 4 5 3]
[5 1 2 4 3]
[1 4 2 3 5]
[2 5 1 4 3]
[1 4 2 3 5]
[3 4 2 1 5]
[3 1 5 4 2]
[5 2 4 1 3]
[2 4 3 5 1]
[3 4 2 1 5]
[2 4 3 5 1]
[5 3 2 4 1]
[4 3 5 1 2]
[1 2 5 3 4]
[3 5 1 2 4]
